import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { ArrowUpRight, Bot, Check, Database, FilePenLine, GitBranch, HeartHandshake, Megaphone, MessageCircle, Network, ShieldCheck, Sparkles, Users, Workflow } from "lucide-react";
import "./styles.css";

const legacyRally = /^\/(room|join)\//.test(location.pathname);
if (legacyRally) location.replace(`https://rally.fanpilot.app${location.pathname}${location.search}${location.hash}`);
else createRoot(document.getElementById("root")!).render(<StrictMode><Portal /></StrictMode>);

const apps = [
  { name:"Rally", icon:HeartHandshake, color:"violet", url:"https://rally.fanpilot.app", tag:"Coordinate a group decision", text:"A shared planning room turns chat into constraints, three viable options, a vote, and a durable final plan.", input:"Multi-user chat + voting", state:"Room messages, constraints, proposals and votes", workflow:"Versioned proposal generation" },
  { name:"Draft", icon:FilePenLine, color:"blue", url:"https://editor.fanpilot.app", tag:"Write together with reviewable AI", text:"A realtime collaborative editor lets teams request targeted rewrites and accept or reject every proposed change.", input:"Rich text + AI chat + comments", state:"Yjs updates, suggestions, revisions and access", workflow:"Snapshot-based AI edit generation" },
  { name:"Launch Relay", icon:Megaphone, color:"green", url:"https://launch.fanpilot.app", tag:"Turn a release into an accurate campaign", text:"Release notes become confirmed facts and three source-linked posts whose approvals react safely when the source changes.", input:"Release source + clarification chat", state:"Facts, post revisions, approvals and publication records", workflow:"Release analysis + campaign generation" },
];

function Portal(){return <main><nav><span className="logo"><Sparkles/><strong>Fanpilot</strong></span><a href="https://github.com/beejmaxx/fanpilot-cloudflare-ai-apps">View source <ArrowUpRight/></a></nav><section className="hero"><span className="kicker"><ShieldCheck/> CLOUDFLARE AI APPLICATION CHALLENGE</span><h1>Three useful products.<br/><em>One Cloudflare-native stack.</em></h1><p>Each live application combines Llama 3.3, durable coordination, conversational input, and persistent memory. Open one and inspect the implementation behind it.</p><div className="requirements"><span><Bot/> Workers AI</span><span><Workflow/> Workflows</span><span><Network/> Durable Objects</span><span><MessageCircle/> Realtime input</span><span><Database/> SQLite state</span></div></section><section className="apps"><div className="section-title"><span>LIVE APPLICATIONS</span><h2>Choose a product to try</h2></div><div className="cards">{apps.map((app)=><article className={app.color} key={app.name}><div className="card-top"><span className="app-icon"><app.icon/></span><span className="live"><i/> LIVE</span></div><span className="tag">{app.tag}</span><h3>{app.name}</h3><p>{app.text}</p><dl><div><dt><MessageCircle/> Input</dt><dd>{app.input}</dd></div><div><dt><GitBranch/> Coordination</dt><dd>{app.workflow}</dd></div><div><dt><Database/> Memory</dt><dd>{app.state}</dd></div></dl><a href={app.url}>Open {app.name} <ArrowUpRight/></a></article>)}</div></section><section className="architecture"><div><span className="kicker">WHY THESE PRIMITIVES</span><h2>The AI works inside a durable product.</h2><p>Workers serve each interface and API. A SQLite-backed Durable Object owns each room, document, or launch workspace. Workflows run recoverable model jobs away from the realtime path, and validated results return as proposals that people can review.</p></div><div className="flow"><span>Browser input</span><b>→</b><span>Cloudflare Worker</span><b>→</b><span>Durable Object + SQLite</span><b>→</b><span>Workflow + Llama 3.3</span></div></section><section className="proof"><div><Users/><h3>User input</h3><p>Chat, collaborative writing, comments, votes, release sources, and approvals.</p></div><div><GitBranch/><h3>Coordination</h3><p>One authoritative Durable Object plus retryable, version-aware Workflows.</p></div><div><Database/><h3>Memory</h3><p>Persistent identities, history, AI proposals, and decisions in SQLite.</p></div><div><Check/><h3>Human control</h3><p>Model output is validated and remains reviewable before it changes shared state.</p></div></section><footer><span>Built for the Cloudflare AI application challenge</span><div><a href="https://github.com/beejmaxx/fanpilot-cloudflare-ai-apps/blob/main/PROMPTS.md">Prompt history</a><a href="https://github.com/beejmaxx/fanpilot-cloudflare-ai-apps">Architecture and tests</a></div></footer></main>}
