import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, CheckCircle2, Clock3, Code2, Copy, Link2, Megaphone, MessageSquare, RefreshCw, Rocket, Send, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import type { CampaignPost, RelaySnapshot, ReleaseFact, WorkspaceSession } from "../shared/types";
import { isReadyToPost } from "../shared/logic";
import { api, body, createWorkspace, session } from "./api";
import { find, recent, save, type SavedWorkspace } from "./storage";
import Turnstile from "./Turnstile";

type Route = { kind: "home" } | { kind: "workspace"; id: string } | { kind: "join"; id: string };

export default function App() {
  const [route, setRoute] = useState<Route>(() => parseRoute());
  useEffect(() => { const handler = () => setRoute(parseRoute()); addEventListener("popstate", handler); return () => removeEventListener("popstate", handler); }, []);
  const go = (path: string) => { history.pushState({}, "", path); setRoute(parseRoute()); };
  if (route.kind === "home") return <Home onOpen={(id) => go(`/launch/${id}`)} />;
  if (route.kind === "join") return <Join id={route.id} onJoined={(id) => go(`/launch/${id}`)} />;
  return <Workspace id={route.id} onHome={() => go("/")} />;
}

function Home({ onOpen }: { onOpen(id: string): void }) {
  const [form, setForm] = useState({ productName: "", website: "https://", audience: "", tone: "Clear, specific, and confident", displayName: "", campaignTitle: "", sourceKind: "notes" as "notes" | "github", sourceBody: "", sourceUrl: "" });
  const [token, setToken] = useState<string | null>(null); const [resetKey, setResetKey] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const update = (key: string, value: string) => setForm((v) => ({ ...v, [key]: value }));
  const sample = () => setForm((v) => ({ ...v, productName: "Draft", website: "https://editor.fanpilot.app", audience: "Small teams writing product specs and proposals", campaignTitle: "Collaborative AI editing launch", sourceKind: "notes", sourceBody: "Draft now supports realtime collaborative editing with named presence. Teams can ask Llama 3.3 for paragraph rewrites and review a before-and-after suggestion before accepting it. Private invitation and return links restore the correct participant without requiring an account." }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!token) return; setBusy(true); setError("");
    try { const result = await createWorkspace({ ...form, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, turnstileToken: token }); remember(result); onOpen(result.workspaceId); }
    catch (e) { setError(e instanceof Error ? e.message : "Could not create launch"); setResetKey((v) => v + 1); setToken(null); } finally { setBusy(false); }
  };
  return <main className="home">
    <nav><Brand /><span className="challenge-pill"><ShieldCheck /> Cloudflare AI challenge</span></nav>
    <section className="hero">
      <div className="hero-copy"><span className="eyebrow">From release notes to launch-ready copy</span><h1>Ship the product.<br/><em>Relay the story.</em></h1><p>Launch Relay turns what changed into three accurate social posts, then keeps every approved claim tied to a confirmed release fact.</p><button className="sample" onClick={sample}><Sparkles /> Load a real example</button>
        <div className="trust"><span><CheckCircle2/> Source-linked facts</span><span><CheckCircle2/> Human approval</span><span><CheckCircle2/> Durable campaign memory</span></div>
      </div>
      <form className="create" onSubmit={submit}><div className="form-title"><Rocket/><div><h2>Start a launch</h2><p>One release. Three coordinated posts.</p></div></div>
        <div className="two"><label>Product name<input aria-label="Product name" value={form.productName} onChange={(e)=>update("productName",e.target.value)} required /></label><label>Your name<input aria-label="Your name" value={form.displayName} onChange={(e)=>update("displayName",e.target.value)} required /></label></div>
        <label>Product website<input aria-label="Product website" type="url" value={form.website} onChange={(e)=>update("website",e.target.value)} required /></label>
        <label>Who is this for?<input aria-label="Audience" value={form.audience} onChange={(e)=>update("audience",e.target.value)} placeholder="Small product teams" required /></label>
        <label>Launch title<input aria-label="Launch title" value={form.campaignTitle} onChange={(e)=>update("campaignTitle",e.target.value)} placeholder="September product update" required /></label>
        <div className="source-tabs"><button type="button" className={form.sourceKind==="notes"?"active":""} onClick={()=>update("sourceKind","notes")}>Paste notes</button><button type="button" className={form.sourceKind==="github"?"active":""} onClick={()=>update("sourceKind","github")}><Code2/> GitHub repository</button></div>
        {form.sourceKind === "notes" ? <textarea aria-label="Release notes" value={form.sourceBody} onChange={(e)=>update("sourceBody",e.target.value)} placeholder="What shipped? Paste release notes, a changelog, or your own summary." required /> : <label className="github-source">Repository or release URL<input aria-label="GitHub repository or release URL" type="url" value={form.sourceUrl} onChange={(e)=>update("sourceUrl",e.target.value)} placeholder="https://github.com/cloudflare/workers-sdk" required /><small>Relay finds the latest published release with useful notes. Paste an exact release URL to choose a specific tag.</small></label>}
        <Turnstile resetKey={resetKey} onToken={useCallback((value:string|null)=>setToken(value),[])} />
        {error && <p role="alert" className="error">{error}</p>}<button className="primary create-button" disabled={!token||busy}>{busy?"Creating launch…":"Create launch"}<ArrowRight/></button>
      </form>
    </section>
    {recent().length > 0 && <section className="recent"><h2>Recent launches</h2><div>{recent().map((item)=><button key={item.id} onClick={()=>onOpen(item.id)}><Megaphone/><span><strong>{item.productName}</strong><small>Continue launch</small></span><ArrowRight/></button>)}</div></section>}
  </main>;
}

function Join({ id, onJoined }: { id:string; onJoined(id:string):void }) {
  const invite = fragment("invite"); const [name,setName]=useState(""); const [info,setInfo]=useState<{productName:string;role:string}|null>(null); const [error,setError]=useState("");
  useEffect(()=>{ if(!invite){setError("This invitation is missing its private token");return;} api<{productName:string;role:string}>(`/api/workspaces/${id}/invitation-info`,{method:"POST",body:body({inviteToken:invite})}).then(setInfo).catch((e)=>setError(e.message));},[id,invite]);
  const join=async(e:React.FormEvent)=>{e.preventDefault();try{const result=await api<WorkspaceSession>(`/api/workspaces/${id}/join`,{method:"POST",body:body({displayName:name,inviteToken:invite})});remember(result);history.replaceState({},"",`/launch/${id}`);onJoined(id);}catch(err){setError(err instanceof Error?err.message:"Could not join");}};
  return <main className="center"><div className="join-card"><Brand/><Users/><h1>{info?`Join ${info.productName}`:"Opening invitation…"}</h1><p>{info?`You were invited as an ${info.role}. Choose the name teammates will see.`:"Checking this single-use invitation."}</p>{error&&<p role="alert" className="error">{error}</p>}<form onSubmit={join}><input aria-label="Your name" value={name} onChange={(e)=>setName(e.target.value)} placeholder="Your name" required/><button className="primary" disabled={!info}>Join launch <ArrowRight/></button></form></div></main>;
}

function Workspace({ id, onHome }: { id:string; onHome():void }) {
  const [auth,setAuth]=useState<SavedWorkspace|undefined>(()=>consumeAccess(id)??find(id)); const [snap,setSnap]=useState<RelaySnapshot|null>(null); const [error,setError]=useState(""); const [share,setShare]=useState(false); const [sourceOpen,setSourceOpen]=useState(false);
  useEffect(()=>{ if(!auth)return; session(id,auth.token).then((result)=>{remember(result);setAuth(find(id));setSnap(result.snapshot);}).catch((e)=>setError(e.message)); },[id,auth?.token]);
  useEffect(()=>{ if(!auth)return; const protocol=location.protocol==="https:"?"wss":"ws"; const ws=new WebSocket(`${protocol}://${location.host}/api/workspaces/${id}/ws`,["relay-v1",auth.token]); ws.onmessage=(e)=>{const value=JSON.parse(e.data);if(value.type==="snapshot")setSnap(value.snapshot)}; ws.onclose=()=>setTimeout(()=>setSnap((v)=>v?{...v}:v),1000); return()=>ws.close();},[id,auth?.token]);
  if(!auth) return <Private onHome={onHome}/>; if(error&&!snap) return <Private onHome={onHome} message={error}/>; if(!snap)return <main className="loading"><Brand/><span/><p>Opening your launch…</p></main>;
  const mutate=async(path:string,init:RequestInit)=>{setError("");try{const result=await api<RelaySnapshot|{snapshot:RelaySnapshot}>(`/api/workspaces/${id}/${path}`,init,auth.token);setSnap("snapshot" in result?result.snapshot:result);}catch(e){setError(e instanceof Error?e.message:"Request failed");throw e;}};
  const step=snap.campaign.stage==="facts"?1:snap.campaign.stage==="posts"?2:3;
  return <main className="workspace"><header><button className="brand-button" onClick={onHome}><Brand/></button><div className="launch-name"><small>LAUNCH WORKSPACE</small><strong>{snap.campaign.title}</strong></div><div className="header-actions"><span className="people"><Users/>{snap.participants.length}</span><button className="quiet" onClick={()=>setShare(true)}><Link2/> Share</button></div></header>
    <div className="steps">{["Confirm facts","Review posts","Ready to share"].map((label,index)=><div className={step>index+1?"done":step===index+1?"active":""} key={label}><span>{step>index+1?<Check/>:index+1}</span>{label}</div>)}</div>
    {error&&<div role="alert" className="banner">{error}<button onClick={()=>setError("")}><X/></button></div>}
    {snap.activeJob&&<div className={`job ${snap.activeJob.status}`}><Sparkles/><span><strong>{snap.activeJob.status==="failed"?"AI job needs another try":snap.activeJob.kind==="analysis"?"Reading the release":"Drafting the campaign"}</strong> {snap.activeJob.status==="failed"?(snap.activeJob.error||"The Workflow failed. Your workspace is intact."):"The Workflow is running; you can leave and return."}</span>{snap.activeJob.status==="running"&&<i/>}</div>}
    <section className="workspace-grid"><div className="main-column">
      <div className="section-head"><div><span className="eyebrow">{step===1?"Source → facts":"Facts → campaign"}</span><h1>{step===1?"Confirm what actually shipped":"Review every post before it goes out"}</h1><p>{step===1?"Relay extracted these claims from your source. Edit anything that needs context, then confirm it.":"Each post names the facts it depends on. Editing copy clears its approval."}</p></div><button className="quiet" onClick={()=>setSourceOpen(!sourceOpen)}><RefreshCw/> {sourceOpen?"Hide source":snap.activeJob?.status==="failed"&&snap.activeJob.kind==="analysis"?"Retry from source":"Review source"}</button></div>
      {sourceOpen&&<SourceEditor snap={snap} onSave={(data)=>mutate("source",{method:"POST",body:body(data)})}/>}
      {step===1?<Facts snap={snap} mutate={mutate}/>:<Posts snap={snap} mutate={mutate}/>}
    </div><aside><CampaignBrief snap={snap}/><Chat snap={snap} onSend={(value)=>mutate("chat",{method:"POST",body:body({body:value,clientId:crypto.randomUUID()})})}/></aside></section>
    {share&&<Share id={id} auth={auth} snap={snap} close={()=>setShare(false)} mutate={mutate}/>}
  </main>;
}

function Facts({snap,mutate}:{snap:RelaySnapshot;mutate(path:string,init:RequestInit):Promise<void>}) {
  const all=snap.facts.length>0&&snap.facts.every((f)=>f.confirmed); return <div className="facts"><div className="question"><MessageSquare/><div><strong>One thing to clarify</strong><p>{snap.campaign.question||"Confirm what customers can use and when."}</p></div></div>{snap.facts.map((fact)=><FactCard key={`${fact.id}-${fact.revision}`} fact={fact} disabled={snap.participant.role==="viewer"} save={(value,confirmed)=>mutate(`facts/${fact.id}`,{method:"PATCH",body:body({value,confirmed,expectedRevision:fact.revision})})}/>) }<div className="next"><div><strong>{all?"Facts confirmed":"Confirm every fact to continue"}</strong><p>{all?"Relay can now draft copy grounded in this release.":`${snap.facts.filter((f)=>!f.confirmed).length} still need your review.`}</p></div><button className="primary" disabled={!all||snap.activeJob?.status==="running"||snap.participant.role==="viewer"} onClick={()=>mutate("generate",{method:"POST"})}>Generate three posts <Sparkles/></button></div></div>;
}
function FactCard({fact,disabled,save}:{fact:ReleaseFact;disabled:boolean;save(value:string,confirmed:boolean):Promise<void>}){const[value,setValue]=useState(fact.value);const[busy,setBusy]=useState(false);const changed=value!==fact.value;return <article className={`fact ${fact.confirmed?"confirmed":""}`}><div className="fact-top"><span>{fact.sourceKind==="release"?"SOURCE FACT":"OWNER DETAIL"}</span>{fact.confirmed&&<b><Check/> Confirmed</b>}</div><label>{fact.label}<textarea value={value} disabled={disabled} onChange={(e)=>setValue(e.target.value)}/></label><blockquote>“{fact.excerpt}”</blockquote>{!disabled&&<div className="fact-actions">{changed&&<button onClick={()=>setValue(fact.value)}>Cancel</button>}<button className={fact.confirmed&&!changed?"quiet":"primary"} disabled={busy||(!changed&&fact.confirmed)} onClick={async()=>{setBusy(true);try{await save(value,true)}finally{setBusy(false)}}}>{fact.confirmed?changed?"Save and reconfirm":"Confirmed":"Confirm fact"}</button></div>}</article>}

function Posts({snap,mutate}:{snap:RelaySnapshot;mutate(path:string,init:RequestInit):Promise<void>}) {return <div className="posts">{snap.posts.map((post,index)=><PostCard key={`${post.id}-${post.revision}-${post.editorialState}-${post.plannedAt}`} post={post} facts={snap.facts} index={index} owner={snap.participant.role==="owner"} viewer={snap.participant.role==="viewer"} mutate={mutate}/>)}{snap.posts.length>0&&<div className="campaign-status"><CheckCircle2/><div><strong>{snap.campaign.stage==="ready"?"Campaign ready":"Finish approvals and planned times"}</strong><p>{snap.campaign.stage==="ready"?"Approved posts become ready in this app when their planned time arrives. Publishing remains manual.":"Nothing will be published automatically."}</p></div></div>}</div>}
function PostCard({post,facts,index,owner,viewer,mutate}:{post:CampaignPost;facts:ReleaseFact[];index:number;owner:boolean;viewer:boolean;mutate(path:string,init:RequestInit):Promise<void>}){const[text,setText]=useState(post.body);const[url,setUrl]=useState("");const changed=text!==post.body;const deps=post.dependencyIds.map((id)=>facts.find((f)=>f.id===id)).filter(Boolean) as ReleaseFact[];const due=isReadyToPost(post,facts);return <article className={`post ${post.editorialState}`}><div className="post-head"><div><span>{post.channel.toUpperCase()}</span><strong>{index===0?"Launch announcement":post.purpose==="feature-follow-up"?"Feature follow-up":"Short announcement"}</strong></div><b>{post.publishedAt?"Published":due?"Ready to post":post.editorialState.replace("_"," ")}</b></div>{post.correctionNeeded&&<div className="correction">Published copy may need a correction because its source changed.</div>}<textarea aria-label={`${post.channel} post`} value={text} disabled={viewer||!!post.publishedAt} onChange={(e)=>setText(e.target.value)}/><div className="based-on"><small>BASED ON</small>{deps.map((f)=><span key={f.id}>{f.label} · v{f.revision}</span>)}</div>{!viewer&&<div className="post-actions">{changed&&<button className="quiet" onClick={()=>setText(post.body)}>Cancel</button>}<button className="quiet" disabled={!changed||!!post.publishedAt} onClick={()=>mutate(`posts/${post.id}`,{method:"PATCH",body:body({body:text,expectedRevision:post.revision})})}>Save copy</button>{owner&&<button className="primary" disabled={changed||post.editorialState==="approved"||!!post.publishedAt} onClick={()=>mutate(`posts/${post.id}/approve`,{method:"POST"})}><Check/> Approve</button>}</div>}{owner&&!post.publishedAt&&<div className="delivery"><label><Clock3/> Planned time<input aria-label={`Planned time for ${post.channel}`} type="datetime-local" value={post.plannedAt?localDateTime(post.plannedAt):""} onChange={(e)=>mutate(`posts/${post.id}/schedule`,{method:"POST",body:body({plannedAt:e.target.value?new Date(e.target.value).getTime():null})})}/></label><button onClick={()=>navigator.clipboard.writeText(post.body)}><Copy/> Copy</button>{post.editorialState==="approved"&&<><input aria-label={`Published URL for ${post.channel}`} type="url" value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="Published URL (optional)"/><button onClick={()=>mutate(`posts/${post.id}/publish`,{method:"POST",body:body(url?{publishedUrl:url}:{})})}>Mark published</button></>}</div>}</article>}

function CampaignBrief({snap}:{snap:RelaySnapshot}){return <section className="brief"><span className="eyebrow">Campaign brief</span><h2>{snap.workspace.productName}</h2><dl><div><dt>Audience</dt><dd>{snap.workspace.audience}</dd></div><div><dt>Tone</dt><dd>{snap.workspace.tone}</dd></div><div><dt>Destination</dt><dd><a href={snap.workspace.website} target="_blank" rel="noreferrer">{snap.workspace.website}</a></dd></div>{snap.campaign.sourceUrl&&<div><dt>Selected release source</dt><dd><a href={snap.campaign.sourceUrl} target="_blank" rel="noreferrer">Open on GitHub</a></dd></div>}<div><dt>Source checked</dt><dd>{new Date(snap.campaign.sourceCheckedAt).toLocaleString()}</dd></div></dl></section>}
function Chat({snap,onSend}:{snap:RelaySnapshot;onSend(value:string):Promise<void>}){const[value,setValue]=useState("");const end=useRef<HTMLDivElement>(null);useEffect(()=>{end.current?.scrollIntoView();},[snap.messages.length]);const submit=async()=>{if(!value.trim())return;const sent=value;setValue("");try{await onSend(sent)}catch{setValue(sent)}};return <section className="chat"><div className="chat-title"><Sparkles/><div><strong>Clarify with AI</strong><small>Answers use your current release context.</small></div></div><div className="messages">{snap.messages.length===0?<p className="empty-chat">Ask what needs confirmation, or how a fact might read to customers.</p>:snap.messages.map((m)=><div key={m.id} className={m.kind}><strong>{m.participantName}</strong><p>{m.body}</p></div>)}<div ref={end}/></div>{snap.participant.role!=="viewer"&&<div className="composer"><textarea aria-label="Ask Launch Relay" value={value} onChange={(e)=>setValue(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void submit()}}} placeholder="Ask about this release…"/><button aria-label="Send message" onClick={submit} disabled={!value.trim()}><Send/></button></div>}</section>}

function SourceEditor({snap,onSave}:{snap:RelaySnapshot;onSave(data:unknown):Promise<void>}){const[kind,setKind]=useState(snap.campaign.sourceKind);const[value,setValue]=useState(snap.campaign.sourceKind==="github"?(snap.campaign.sourceUrl||""):snap.campaign.sourceBody);return <section className="source-editor"><div><strong>Update release source</strong><p>Changing the source clears fact confirmations and invalidates dependent approvals.</p></div><select value={kind} onChange={(e)=>{const next=e.target.value as "notes"|"github";setKind(next);setValue(next==="github"?(snap.campaign.sourceUrl||""):snap.campaign.sourceBody)}}><option value="notes">Pasted release notes</option><option value="github">GitHub repository or release</option></select>{kind==="notes"?<textarea aria-label="Updated release notes" value={value} onChange={(e)=>setValue(e.target.value)}/>:<label className="github-source">Repository or release URL<input aria-label="Updated GitHub repository or release URL" type="url" value={value} onChange={(e)=>setValue(e.target.value)}/><small>A repository URL selects its latest published release with useful notes.</small></label>}<button className="primary" disabled={!value.trim()||snap.participant.role!=="owner"} onClick={()=>onSave({sourceKind:kind,sourceBody:kind==="notes"?value:undefined,sourceUrl:kind==="github"?value:""})}>Analyze updated source</button></section>}

function Share({id,auth,snap,close}:{id:string;auth:SavedWorkspace;snap:RelaySnapshot;close():void;mutate(path:string,init:RequestInit):Promise<void>}){const[role,setRole]=useState("editor");const[invite,setInvite]=useState("");const[copyState,setCopyState]=useState("");const returnLink=`${location.origin}/launch/${id}#access=${auth.token}`;const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value);setCopyState(label);setTimeout(()=>setCopyState(""),1500)};return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={(e)=>e.stopPropagation()}><button className="modal-close" onClick={close}><X/></button><h2>Share this launch</h2><p>Private links restore identities. Use an invitation to add a new teammate.</p><label>My private return link<div className="copy-row"><input readOnly value={returnLink}/><button onClick={()=>copy(returnLink,"return")}>{copyState==="return"?<Check/>:<Copy/>}</button></div><small>Keep this private. It restores your {snap.participant.role} access on another browser.</small></label>{snap.participant.role==="owner"&&<><label>Invite a teammate<select value={role} onChange={(e)=>setRole(e.target.value)}><option value="editor">Editor</option><option value="viewer">Viewer</option></select></label><button className="primary" onClick={async()=>{const result=await api<{invitationUrl:string}>(`/api/workspaces/${id}/invitations`,{method:"POST",body:body({role})},auth.token);setInvite(result.invitationUrl)}}>Create one-time invitation</button>{invite&&<div className="copy-row"><input readOnly value={invite}/><button onClick={()=>copy(invite,"invite")}>{copyState==="invite"?<Check/>:<Copy/>}</button></div>}</>}<button className="rotate" onClick={async()=>{const result=await api<WorkspaceSession>(`/api/workspaces/${id}/participant/rotate-access`,{method:"POST"},auth.token);remember(result);location.assign(`/launch/${id}#access=${result.token}`)}}>Rotate my private link</button></section></div>}

function Private({onHome,message="This workspace ID does not grant access. Open your private return link or ask the owner for an invitation."}:{onHome():void;message?:string}){return <main className="center"><div className="join-card"><Brand/><ShieldCheck/><h1>Private link required</h1><p>{message}</p><button className="quiet" onClick={onHome}>Back to Launch Relay</button></div></main>}
function Brand(){return <span className="brand"><span><Megaphone/></span><strong>Launch Relay</strong></span>}
function parseRoute():Route{const join=location.pathname.match(/^\/join\/([0-9a-f-]{36})$/i);if(join)return{kind:"join",id:join[1]};const launch=location.pathname.match(/^\/launch\/([0-9a-f-]{36})$/i);if(launch)return{kind:"workspace",id:launch[1]};return{kind:"home"}}
function fragment(key:string):string{const params=new URLSearchParams(location.hash.slice(1));return params.get(key)||""}
function consumeAccess(id:string):SavedWorkspace|undefined{const token=fragment("access");if(!token)return;history.replaceState({},"",location.pathname);const item={id,productName:"Launch",token,participantId:"",updatedAt:Date.now()};save(item);return item}
function remember(result:WorkspaceSession){save({id:result.workspaceId,productName:result.snapshot.workspace.productName,token:result.token,participantId:result.participantId,updatedAt:Date.now()})}
function localDateTime(value:number):string{const d=new Date(value);return new Date(value-d.getTimezoneOffset()*60_000).toISOString().slice(0,16)}
